/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./src/components/common/AboutDialog.vue')['default']
    ActionList: typeof import('./src/components/advanced/ActionList.vue')['default']
    ActionRow: typeof import('./src/components/advanced/ActionRow.vue')['default']
    ArmedStartButton: typeof import('./src/components/common/ArmedStartButton.vue')['default']
    HotkeyDisplay: typeof import('./src/components/common/HotkeyDisplay.vue')['default']
    HotkeyInput: typeof import('./src/components/common/HotkeyInput.vue')['default']
    ProfileCard: typeof import('./src/components/advanced/ProfileCard.vue')['default']
    ProfileEditor: typeof import('./src/components/advanced/ProfileEditor.vue')['default']
    ProfileList: typeof import('./src/components/advanced/ProfileList.vue')['default']
    QuickClickCard: typeof import('./src/components/QuickClickCard.vue')['default']
    QuickEditor: typeof import('./src/components/QuickEditor.vue')['default']
    RepeatEditor: typeof import('./src/components/advanced/RepeatEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputNumber: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    UKbd: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    URadioGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USeparator: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
  }
}
